### ISSUE TITLE
Transparent track background color

### ISSUE THREAD

**Issue by catelbow** [lrferreiro/flutter_swipe_button#2]
I had achieved a transparent track background color by setting `activeTrackColor` to `Colors.transparent`. This seems to have broken with the latest update. Now my track color is the `theme.backgroundColor`. From what I've seen in the code, this is the default when no `activeTrackColor` is set. Is there any chance to make a transparent track happen again?

**Comment by lrferreiro** [comment]
Hello, thanks for reporting the bug. He was corrected in the new version.
