### ISSUE TITLE
dispose() called with active Ticker

### ISSUE THREAD

**Issue by catelbow** [lrferreiro/flutter_swipe_button#4]
Hi, thank you for making and maintaining this package!

Swiping the swipe button throws `_SwipeState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().` `Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.`

**Comment by lrferreiro** [comment]
Oh! Thanks, I had completely forgotten about the dispose. I already corrected the error.
Thanks for using the package.
